### ISSUE TITLE
unable to load and read the json file Luvia Theme-color-theme.json

### ISSUE THREAD

**Issue by Xlt3h** [maciekkoks/luvia-vsc-theme#4]
Unable to load file:///home/rich/.vscode/extensions/maciekkoks.luvia-theme-0.1.25/themes/Luvia%20Theme-color-theme.json: Unable to read file '/home/rich/.vscode/extensions/maciekkoks.luvia-theme-0.1.25/themes/Luvia Theme-color-theme.json' (Error: Unable to resolve nonexistent file '/home/rich/.vscode/extensions/maciekkoks.luvia-theme-0.1.25/themes/Luvia Theme-color-theme.json')

**Comment by maciekt07** [comment]
thanks for reporting the issue! Could you clarify if this error pops up specifically when you're trying to set the theme? It seems to be working fine on my end

**Comment by maciekt07** [comment]
Should be fixed now. Let me know if it’s still an issue
